<?php

//--------------------------------------------------------------------------------

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_settings-main-two',
		'title' => esc_html__("Settings main two","crazy"),
		'fields' => array (
			array (
				'key' => 'field_572b6722522c1',
				'label' => esc_html__("Header","crazy"),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_572b68e2522c2',
				'label' => esc_html__("Background image","crazy"),
				'name' => 'background_image0',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_572b7036cee60',
				'label' => esc_html__("Changing titles","crazy"),
				'name' => 'changing_titles',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_572b7108cee61',
						'label' => esc_html__("Header","crazy"),
						'name' => 'header',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => esc_html__("Add header","crazy"),
			),
			array (
				'key' => 'field_572b777abe6b4',
				'label' => esc_html__("Text","crazy"),
				'name' => 'text0',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_572b7839be6b5',
				'label' => esc_html__("Button","crazy"),
				'name' => 'button0',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_572b786abe6b6',
						'label' => esc_html__("Text","crazy"),
						'name' => 'text_u0',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_572b78afbe6b7',
						'label' => esc_html__("Link","crazy"),
						'name' => 'link0',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => esc_html__("Add button","crazy"),
			),
			array (
				'key' => 'field_572b790bc6092',
				'label' => esc_html__("Icons","crazy"),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_572d9ed433303',
				'label' => esc_html__("Display unit","crazy"),
				'name' => 'display_unit2',
				'type' => 'select',
				'choices' => array (
					'show' => esc_html__("Show","crazy"),
					'hide' => esc_html__("Hide","crazy"),
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_572b806a63f98',
				'label' => esc_html__("Blocks","crazy"),
				'name' => 'blocks2',
				'type' => 'repeater',
				'instructions' => '<a target="_blank" href="../wp-content/themes/the_crazy/include/icons.html">'.esc_html__("Available icons","crazy").'</a>',
				'sub_fields' => array (
					array (
						'key' => 'field_572b81a763f99',
						'label' => esc_html__("Icon","crazy"),
						'name' => 'icon2',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_572b81d763f9a',
						'label' => esc_html__("Header","crazy"),
						'name' => 'header2',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_572b81f863f9b',
						'label' => esc_html__("Text","crazy"),
						'name' => 'text2',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => esc_html__("Add block","crazy"),
			),
			array (
				'key' => 'field_572b7fb70aa06',
				'label' => esc_html__("About Us","crazy"),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_572d9e7533302',
				'label' => esc_html__("Display unit","crazy"),
				'name' => 'display_unit1',
				'type' => 'select',
				'choices' => array (
					'show' => esc_html__("Show","crazy"),
					'hide' => esc_html__("Hide","crazy"),
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_572b7dca2ee89',
				'label' => esc_html__("Text","crazy"),
				'name' => 'text1',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_572b7df22ee8a',
				'label' => esc_html__("Link","crazy"),
				'name' => 'link1',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_572b7e562ee8b',
				'label' => esc_html__("Picture","crazy"),
				'name' => 'picture1',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_572b7f700aa05',
				'label' => esc_html__("Text 2","crazy"),
				'name' => 'text11',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_572b8efe6eb1b',
				'label' => esc_html__("What we do","crazy"),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_572d9ef033304',
				'label' => esc_html__("Display unit","crazy"),
				'name' => 'display_unit3',
				'type' => 'select',
				'choices' => array (
					'show' => esc_html__("Show","crazy"),
					'hide' => esc_html__("Hide","crazy"),
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_572b8f446eb1c',
				'label' => esc_html__("Header","crazy"),
				'name' => 'header3',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_572b8f596eb1d',
				'label' => esc_html__("Text","crazy"),
				'name' => 'text3',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_572b8f9c6eb1e',
				'label' => esc_html__("Slider","crazy"),
				'name' => 'slider3',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_572b8fe26eb1f',
						'label' => esc_html__("Header","crazy"),
						'name' => 'header33',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_572b90496eb20',
						'label' => esc_html__("Text","crazy"),
						'name' => 'text333',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
					array (
						'key' => 'field_572b905d6eb21',
						'label' => esc_html__("Link","crazy"),
						'name' => 'link3',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_572b90736eb22',
						'label' => esc_html__("Picture","crazy"),
						'name' => 'picture3',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'url',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => esc_html__("Add slide","crazy"),
			),
			array (
				'key' => 'field_572b9185494d3',
				'label' => esc_html__("Icons 2","crazy"),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_572d9f7333307',
				'label' => esc_html__("Display unit","crazy"),
				'name' => 'display_unit6',
				'type' => 'select',
				'choices' => array (
					'show' =>  esc_html__("Show","crazy"),
					'hide' =>  esc_html__("Hide","crazy"),
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_572b948e8a98b',
				'label' => esc_html__("Blocks","crazy"),
				'name' => 'blocks6',
				'type' => 'repeater',
				'instructions' => '<a target="_blank" href="../wp-content/themes/the_crazy/include/icons.html">'.esc_html__("Available icons","crazy").'</a>',
				'sub_fields' => array (
					array (
						'key' => 'field_572b94b18a98c',
						'label' => esc_html__("Icon","crazy"),
						'name' => 'icon6',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_572b94cc8a98d',
						'label' => esc_html__("Number","crazy"),
						'name' => 'number6',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_572b94e08a98e',
						'label' => esc_html__("Text","crazy"),
						'name' => 'text6',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => esc_html__("Add block","crazy"),
			),
			array (
				'key' => 'field_572b9288c734c',
				'label' => esc_html__("Our works","crazy"),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_572d9f6033306',
				'label' => esc_html__("Display unit","crazy"),
				'name' => 'display_unit5',
				'type' => 'select',
				'choices' => array (
					'show' => esc_html__("Show","crazy"),
					'hide' => esc_html__("Hide","crazy"),
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_572b92bac734d',
				'label' => esc_html__("Header","crazy"),
				'name' => 'header5',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_572b92d0c734e',
				'label' => esc_html__("Text","crazy"),
				'name' => 'text5',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_572b7923c6093',
				'label' => esc_html__("Menu portfolio","crazy"),
				'name' => 'menu_portfolio',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_572b7b2ac6094',
						'label' => esc_html__("Text","crazy"),
						'name' => 'text_u00',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_572c57ca65637',
						'label' => esc_html__("Class filter","crazy"),
						'name' => 'class_filter',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => esc_html__("Add item","crazy"),
			),
			array (
				'key' => 'field_572b93648a989',
				'label' => esc_html__("Id column","crazy"),
				'name' => 'id_column5',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_572d9722a9ca2',
				'label' => esc_html__("Number of posts","crazy"),
				'name' => 'number_of_posts1',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_572b930bc734f',
				'label' => esc_html__("Text button","crazy"),
				'name' => 'text_button5',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_572b931ac7350',
				'label' => esc_html__("Link","crazy"),
				'name' => 'link5',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_572b93958a98a',
				'label' => esc_html__("Reviews","crazy"),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_572d9f8833308',
				'label' => esc_html__("Display unit","crazy"),
				'name' => 'display_unit7',
				'type' => 'select',
				'choices' => array (
					'show' => esc_html__("Show","crazy"),
					'hide' => esc_html__("Hide","crazy"),
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_572c598465638',
				'label' => esc_html__("Background image","crazy"),
				'name' => 'background_image6',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_572c5a8065639',
				'label' => esc_html__("Slider","crazy"),
				'name' => 'slider6',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_572c5aa26563a',
						'label' => esc_html__("Picture","crazy"),
						'name' => 'picture666',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'url',
						'preview_size' => 'full',
						'library' => 'all',
					),
					array (
						'key' => 'field_572c5ae86563b',
						'label' => esc_html__("Text","crazy"),
						'name' => 'text666',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => esc_html__("Add slide","crazy"),
			),
			array (
				'key' => 'field_572b94ec8a98f',
				'label' => esc_html__("Blog","crazy"),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_572d9fa83330a',
				'label' => esc_html__("Display unit","crazy"),
				'name' => 'display_unit9',
				'type' => 'select',
				'choices' => array (
					'show' => esc_html__("Show","crazy"),
					'hide' => esc_html__("Hide","crazy"),
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_572b994a5a23f',
				'label' => esc_html__("Header","crazy"),
				'name' => 'header9',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_572b995d5a240',
				'label' => esc_html__("Text","crazy"),
				'name' => 'text9',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_572b99c87459d',
				'label' => esc_html__("Id column","crazy"),
				'name' => 'id_column9',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_572d9732a9ca3',
				'label' => esc_html__("Number of posts","crazy"),
				'name' => 'number_of_posts2',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_572b99085a23d',
				'label' => esc_html__("Text button","crazy"),
				'name' => 'text_button9',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_572b991c5a23e',
				'label' => esc_html__("Link","crazy"),
				'name' => 'link9',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-home.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'featured_image',
				7 => 'categories',
				8 => 'tags',
				9 => 'send-trackbacks',
			),
		),
		'menu_order' => 1,
	));
}

//--------------------------------------------------------------------------------

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_settings-about-us-two',
		'title' => esc_html__("Settings about us two","crazy"),
		'fields' => array (
			array (
				'key' => 'field_5731941df1911',
				'label' => esc_html__("Icons","crazy"),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_573194daf1912',
				'label' => esc_html__("Display unit","crazy"),
				'name' => 'display_unit2',
				'type' => 'select',
				'choices' => array (
					'show' => esc_html__("Show","crazy"),
					'hide' => esc_html__("Hide","crazy"),
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_573194fbf1913',
				'label' => esc_html__("Blocks","crazy"),
				'name' => 'blocks1',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_57319520f1914',
						'label' => esc_html__("icon","crazy"),
						'name' => 'icon1',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_57319530f1915',
						'label' => esc_html__("Header","crazy"),
						'name' => 'header1',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_57319540f1916',
						'label' => esc_html__("Text","crazy"),
						'name' => 'text1',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => esc_html__("Add block","crazy"),
			),
			array (
				'key' => 'field_573191126e0a2',
				'label' => esc_html__("About","crazy"),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5731917a6e0a3',
				'label' => esc_html__("Display unit","crazy"),
				'name' => 'display_unit1',
				'type' => 'select',
				'choices' => array (
					'show' => esc_html__("Show","crazy"),
					'hide' => esc_html__("Hide","crazy"),
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_573192356e0a4',
				'label' => esc_html__("Picture","crazy"),
				'name' => 'picture0',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_573192646e0a5',
				'label' => esc_html__("Texts","crazy"),
				'name' => 'texts',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5731928e6e0a6',
						'label' => esc_html__("Text","crazy"),
						'name' => 'text0',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => esc_html__("Add text","crazy"),
			),
			array (
				'key' => 'field_5731937b6e9d5',
				'label' => esc_html__("Text","crazy"),
				'name' => 'text00',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_573195eccfe82',
				'label' => esc_html__("Our Skills","crazy"),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_573195f5cfe83',
				'label' => esc_html__("Display unit","crazy"),
				'name' => 'display_unit3',
				'type' => 'select',
				'choices' => array (
					'show' => esc_html__("Show","crazy"),
					'hide' => esc_html__("Hide","crazy"),
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_573196dacfe84',
				'label' => esc_html__("Header","crazy"),
				'name' => 'header2',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_573196efcfe85',
				'label' => esc_html__("Text","crazy"),
				'name' => 'text2',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5731975bcfe86',
				'label' => esc_html__("Progress bar 1","crazy"),
				'name' => 'progress_bar1',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_57319777cfe87',
						'label' => esc_html__("Description","crazy"),
						'name' => 'description3',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5731978fcfe88',
						'label' => esc_html__("Progress","crazy"),
						'name' => 'progress3',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => 0,
						'max' => 100,
						'step' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => esc_html__("Add","crazy"),
			),
			array (
				'key' => 'field_573197b7cfe89',
				'label' => esc_html__("Progress bar 2","crazy"),
				'name' => 'progress_bar2',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_573197eecfe8a',
						'label' => esc_html__("Description","crazy"),
						'name' => 'description33',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_573197fccfe8b',
						'label' => esc_html__("Progress","crazy"),
						'name' => 'progress33',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => 0,
						'max' => 100,
						'step' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => esc_html__("Add","crazy"),
			),
			array (
				'key' => 'field_5731a55508e80',
				'label' => esc_html__("Icons 2","crazy"),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5731a56508e81',
				'label' => esc_html__("Display unit","crazy"),
				'name' => 'display_unit6',
				'type' => 'select',
				'choices' => array (
					'show' => esc_html__("Show","crazy"),
					'hide' => esc_html__("Hide","crazy"),
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5731a61808e82',
				'label' => esc_html__("Blocks","crazy"),
				'name' => 'blocks6',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5731a63308e83',
						'label' => esc_html__("Icon","crazy"),
						'name' => 'icon6',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5731a64608e84',
						'label' => esc_html__("Number","crazy"),
						'name' => 'number6',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_5731a66008e85',
						'label' => esc_html__("Text","crazy"),
						'name' => 'text6',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => esc_html__("Add block","crazy"),
			),
			array (
				'key' => 'field_5731a1d78b704',
				'label' => esc_html__("Our team","crazy"),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5731a1e08b705',
				'label' => esc_html__("Display unit","crazy"),
				'name' => 'display_unit5',
				'type' => 'select',
				'choices' => array (
					'show' => esc_html__("Show","crazy"),
					'hide' => esc_html__("Hide","crazy"),
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5731a2028b706',
				'label' => esc_html__("header","crazy"),
				'name' => 'header5',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5731a3158b707',
				'label' => esc_html__("Text","crazy"),
				'name' => 'text5',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5731a35b8b708',
				'label' => esc_html__("Blocks","crazy"),
				'name' => 'blocks5',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5731a38a8b709',
						'label' => esc_html__("Picture","crazy"),
						'name' => 'picture5',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'url',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_5731a3ff8b70a',
						'label' => esc_html__("Header","crazy"),
						'name' => 'header55',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5731a41f8b70b',
						'label' => esc_html__("Text","crazy"),
						'name' => 'text55',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5731a4308b70c',
						'label' => esc_html__("Link to facebook.com","crazy"),
						'name' => 'link_to_facebook5',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5731a4478b70d',
						'label' => esc_html__("Link to dribbble.com","crazy"),
						'name' => 'link_to_dribbble5',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5731a45d8b70e',
						'label' => esc_html__("Link on twitter.com","crazy"),
						'name' => 'link_on_twitter5',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => esc_html__("Add block","crazy"),
			),
			array (
				'key' => 'field_5731a7530e3f5',
				'label' => esc_html__("Reviews","crazy"),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5731a7580e3f6',
				'label' => esc_html__("Display unit","crazy"),
				'name' => 'display_unit7',
				'type' => 'select',
				'choices' => array (
					'show' => esc_html__("Show","crazy"),
					'hide' => esc_html__("Hide","crazy"),
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_7777ad23506ab',
				'label' => esc_html__("Background image","crazy"),
				'name' => 'picture777',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5731a7d40e3f8',
				'label' => esc_html__("Reviews","crazy"),
				'name' => 'reviews7',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5731a7f30e3f9',
						'label' => esc_html__("Recall","crazy"),
						'name' => 'recall7',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
					array (
						'key' => 'field_5731adcc506ac',
						'label' => esc_html__("Picture","crazy"),
						'name' => 'picture77',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'url',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => esc_html__("Add a review","crazy"),
			),
			array (
				'key' => 'field_5731ae62506ad',
				'label' => esc_html__("Clients","crazy"),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5731ae85506ae',
				'label' => esc_html__("Display unit","crazy"),
				'name' => 'display_unit8',
				'type' => 'select',
				'choices' => array (
					'show' => esc_html__("Show","crazy"),
					'hide' => esc_html__("Hide","crazy"),
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5731ae91506af',
				'label' => esc_html__("Logos","crazy"),
				'name' => 'logos8',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5731aeac506b0',
						'label' => esc_html__("Logo","crazy"),
						'name' => 'logo8',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'url',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => esc_html__("Add logo","crazy"),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-about-us.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'categories',
				6 => 'tags',
				7 => 'send-trackbacks',
			),
		),
		'menu_order' => 1,
	));
}

//--------------------------------------------------------------------------------

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_settings-portfolio-two',
		'title' => esc_html__("Settings portfolio - two","crazy"),
		'fields' => array (
			array (
				'key' => 'field_5735b3979a6d8',
				'label' => esc_html__("Post","crazy"),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5736ddacf7cec',
				'label' => esc_html__("Gallery","crazy"),
				'name' => 'gallery',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5736ddbaf7ced',
						'label' => esc_html__("Picture","crazy"),
						'name' => 'picture',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'url',
						'preview_size' => 'medium',
						'library' => 'all',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => esc_html__("Add a photo","crazy"),
			),
			array (
				'key' => 'field_5736e43389b43',
				'label' => esc_html__("Blocks","crazy"),
				'name' => 'blocks',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5736e45589b44',
						'label' => esc_html__("Text 1","crazy"),
						'name' => 'text_1',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5736e46689b45',
						'label' => esc_html__("Text 2","crazy"),
						'name' => 'text_2',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => esc_html__("Add block","crazy"),
			),
			array (
				'key' => 'field_5735d0566cc0f',
				'label' => esc_html__("Background header","crazy"),
				'name' => 'background_header',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5735b3a89a6d9',
				'label' => esc_html__("Category","crazy"),
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5735b3c39a6da',
				'label' => esc_html__("Class filter","crazy"),
				'name' => 'class_filter',
				'type' => 'text',
				'instructions' => esc_html__("Example: 1) class; 2) class1 class2","crazy"),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'gallery',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'excerpt',
				1 => 'custom_fields',
				2 => 'discussion',
				3 => 'comments',
				4 => 'send-trackbacks',
			),
		),
		'menu_order' => 1,
	));
}

?>